from __future__ import annotations

import asyncio
import os
import signal
from collections.abc import Awaitable, Callable
from pathlib import Path

from .models import InstrumentConfig, InstrumentMode, PtpProfile

LineCallback = Callable[[str], Awaitable[None]]


def render_ptp4l_config(
    config: InstrumentConfig, mode: InstrumentMode, profile: PtpProfile | None = None
) -> str:
    profile = profile or config.selected_profile()
    server_only = mode == InstrumentMode.GRANDMASTER
    client_only = mode in {InstrumentMode.SLAVE, InstrumentMode.ANALYZER}
    transport = "L2" if profile.transport.value == "L2" else "UDPv4"
    timestamping = "hardware" if config.hardware_timestamping else "software"
    lines = [
        "# Generated by BeaglePTP. Manual edits are overwritten.",
        "[global]",
        f"domainNumber                 {profile.domain}",
        f"network_transport            {transport}",
        f"delay_mechanism              {profile.delay_mechanism.value}",
        f"time_stamping                {timestamping}",
        f"twoStepFlag                  {1 if config.two_step else 0}",
        f"transportSpecific            {profile.transport_specific}",
        f"logSyncInterval              {profile.log_sync_interval}",
        f"logAnnounceInterval          {profile.log_announce_interval}",
        f"announceReceiptTimeout       {profile.announce_receipt_timeout}",
        f"priority1                    {profile.priority1}",
        f"priority2                    {profile.priority2}",
        f"clockClass                   {profile.clock_class}",
        f"clockAccuracy                {profile.clock_accuracy}",
        f"offsetScaledLogVariance      {profile.offset_scaled_log_variance}",
        f"serverOnly                   {1 if server_only else 0}",
        f"clientOnly                   {1 if client_only else 0}",
        f"free_running                 {1 if mode == InstrumentMode.ANALYZER else 0}",
        # Keep the reporting window below common 8 Hz broadcast profiles so
        # ptp4l emits signed ``master offset`` samples instead of aggregate
        # ``rms`` lines. The latter do not contain a signed instantaneous TE.
        "summary_interval             -4",
        "logging_level                6",
        "use_syslog                   0",
        "verbose                      1",
        f"uds_address                  {Path(config.runtime_dir) / 'ptp4l'}",
        f"uds_ro_address               {Path(config.runtime_dir) / 'ptp4lro'}",
        "",
        f"[{config.interface}]",
        "",
    ]
    return "\n".join(lines)


class ManagedProcess:
    """Async subprocess with process-group shutdown and streamed output."""

    def __init__(self, name: str, argv: list[str], line_callback: LineCallback) -> None:
        self.name = name
        self.argv = argv
        self.line_callback = line_callback
        self.process: asyncio.subprocess.Process | None = None
        self.reader_task: asyncio.Task[None] | None = None

    @property
    def running(self) -> bool:
        return self.process is not None and self.process.returncode is None

    async def start(self) -> None:
        if self.running:
            raise RuntimeError(f"{self.name} is already running")
        self.process = await asyncio.create_subprocess_exec(
            *self.argv,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            start_new_session=True,
        )
        self.reader_task = asyncio.create_task(self._read_output(), name=f"{self.name}-reader")

    async def _read_output(self) -> None:
        assert self.process is not None and self.process.stdout is not None
        while line := await self.process.stdout.readline():
            await self.line_callback(line.decode(errors="replace").rstrip())

    async def stop(self, timeout: float = 5.0) -> None:
        if not self.process:
            return
        process = self.process
        if process.returncode is None:
            os.killpg(process.pid, signal.SIGTERM)
            try:
                await asyncio.wait_for(process.wait(), timeout=timeout)
            except TimeoutError:
                os.killpg(process.pid, signal.SIGKILL)
                await process.wait()
        if self.reader_task:
            await self.reader_task
        self.process = None
        self.reader_task = None


class LinuxPtpBackend:
    def __init__(self, config: InstrumentConfig, line_callback: LineCallback) -> None:
        self.config = config
        self.line_callback = line_callback
        self.processes: dict[str, ManagedProcess] = {}
        self.active_config_path: Path | None = None

    async def start(self, mode: InstrumentMode) -> Path:
        if self.processes:
            raise RuntimeError("linuxptp backend is already active")
        if mode not in {InstrumentMode.ANALYZER, InstrumentMode.GRANDMASTER, InstrumentMode.SLAVE}:
            raise ValueError(f"unsupported linuxptp mode: {mode}")
        runtime = Path(self.config.runtime_dir)
        runtime.mkdir(parents=True, exist_ok=True)
        self.active_config_path = runtime / "ptp4l.conf"
        self.active_config_path.write_text(render_ptp4l_config(self.config, mode), encoding="utf-8")
        # The generated [interface] section already declares the port. Supplying
        # it again with -i can create a duplicate port on some linuxptp versions.
        ptp4l_argv = ["ptp4l", "-f", str(self.active_config_path), "-m"]
        if self.config.hardware_timestamping:
            ptp4l_argv.extend(["-p", self.config.ptp_device])
        try:
            ptp4l = ManagedProcess("ptp4l", ptp4l_argv, self.line_callback)
            self.processes["ptp4l"] = ptp4l
            await ptp4l.start()

            # Read-only analysis measures but does not discipline PHC or system time.
            if mode != InstrumentMode.ANALYZER or not self.config.read_only_analyzer:
                socket_path = str(runtime / "ptp4l")
                domain = str(self.config.selected_profile().domain)
                if mode == InstrumentMode.GRANDMASTER:
                    argv = [
                        "phc2sys",
                        "-c",
                        self.config.ptp_device,
                        "-s",
                        "CLOCK_REALTIME",
                        "-w",
                        "-z",
                        socket_path,
                        "-n",
                        domain,
                        "-m",
                    ]
                else:
                    argv = ["phc2sys", "-a", "-r", "-z", socket_path, "-n", domain, "-m"]
                phc2sys = ManagedProcess("phc2sys", argv, self.line_callback)
                self.processes["phc2sys"] = phc2sys
                await phc2sys.start()
        except Exception:
            await self.stop()
            raise
        return self.active_config_path

    async def stop(self) -> None:
        for process in reversed(list(self.processes.values())):
            await process.stop()
        self.processes.clear()

    async def query(self, management_id: str) -> str:
        allowed = {
            "DEFAULT_DATA_SET",
            "CURRENT_DATA_SET",
            "PARENT_DATA_SET",
            "TIME_PROPERTIES_DATA_SET",
            "PORT_DATA_SET",
        }
        if management_id not in allowed:
            raise ValueError("unsupported management ID")
        process = await asyncio.create_subprocess_exec(
            "pmc",
            "-u",
            "-b",
            "0",
            "-s",
            str(Path(self.config.runtime_dir) / "ptp4lro"),
            "-d",
            str(self.config.selected_profile().domain),
            "-t",
            str(self.config.selected_profile().transport_specific),
            f"GET {management_id}",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=3)
        if process.returncode:
            raise RuntimeError(stderr.decode(errors="replace").strip() or "pmc failed")
        return stdout.decode(errors="replace")
